version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - /home/vagrant/example:/var/www
        ports:
            - "8080:80"